In [1]:
import numpy as np

create a five element array using your fave nums

In [2]:
myFavorites=np.array([7,8,13,21,88])

perform each of the five aggregate functions

In [3]:
myFavorites.max()

88

In [4]:
myFavorites.min()

7

In [5]:
myFavorites.mean()

27.4

In [6]:
myFavorites.sum()

137

In [7]:
myFavorites.std()

30.70244289954791

create a five element array containing only ones

In [8]:
OneArrayToRuleThemAll=np.ones(5)

add your faves array and the ones array

In [9]:
myFavorites+OneArrayToRuleThemAll

array([ 8.,  9., 14., 22., 89.])

multiply every element in your faves by 2

In [10]:
myFavorites*2

array([ 14,  16,  26,  42, 176])

call the 3rd element in my faves using indexing

In [11]:
myFavorites[2]

13

create a four element, 2by2 matrix

In [12]:
TheMatrixHasYou=np.array([[4,3], [10,19]])

access the upper left element in the matrix using indexing

In [13]:
print(TheMatrixHasYou)

[[ 4  3]
 [10 19]]


In [14]:
TheMatrixHasYou[0,0]

4

find the largest num in ea row of the matrix

In [15]:
TheMatrixHasYou.max(axis=1)

array([ 4, 19])

reshape the matrix into one row and four columns

In [16]:
TheMatrixHasYou.reshape(1,4)

array([[ 4,  3, 10, 19]])